### ISSUE TITLE
do the lectures correspond to the current semesters course?

### ISSUE THREAD

**Issue by black-fake** [jschildgen/dwh-slides#1]
I take your course data warehouse this semester and realized, that you use newer lecture notes than are available in this repository.
Or at least it seems like that to me.

**Comment by black-fake** [comment]
at least this is true for the first few notes (organizational themes like exam, dates and so on)

**Comment by jschildgen** [comment]
Yes, this semester's data-warehousing course at the OTH Regensburg uses the slides on this repository. This final version of the slides will be pushed to the repository in August.
